# Generated by Django 4.2 on 2024-10-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_comment_name_alter_reply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='content',
            field=models.TextField(default='good teacher'),
        ),
    ]
