# Generated by Django 4.2 on 2024-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltoken',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
