# Generated by Django 4.2 on 2024-08-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='created_at',
        ),
    ]
